### ISSUE TITLE
Setting column layout - shipping manager

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#191]
Object reference not set to an instance of an object.
   at Intelogy___Business_Manager.v8_Global_Functions.SaveGridControlLayout(GridView& GridviewObj, BarStaticItem& StaticItem, String FormName, String ControlName, layoutTypes layoutSetting)
   at Intelogy___Business_Manager.v8_Tools_ShippingManager._Closure$__1248-0._Lambda$__1()
   at Intelogy___Business_Manager.v8_Tools_ShippingManager._Closure$__1248-0._Lambda$__R2(Object a0, EventArgs a1)
   at DevExpress.Utils.Menu.DXMenuItem.OnClick()
   at DevExpress.XtraBars.Utils.DXPopupXtraMenu.OnBarMenuClick(Object sender, ItemClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at DevExpress.XtraBars.Controls.CustomPopupBarControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by bLeenstra** [comment]
Fixed in v369
