### ISSUE TITLE
Bug Report - Publish Design in PDF Input Management

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#70]
I tried clicking publish design and naming it samsung. however throws this error up.

Also using your bug report button only showed this much of the data.

> Conversion from type 'DBNull' to type 'Boolean' is not valid.   at Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(Object Value)   at Intelogy___Business_Manager.v8_Tools_PDfExtractor.SyncRsToKeys()   at Intelogy___Business_Manager.v8_Tools_PDfExtractor.SimpleButton3_Click(Object sender, EventArgs e)   at System.Windows.Forms.Control.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)   at System.Windows.Forms.Control.WmMouseUp(Message

### Exception Information -2147467262
Conversion from type 'DBNull' to type 'Boolean' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(Object Value)
   at Intelogy___Business_Manager.v8_Tools_PDfExtractor.SyncRsToKeys()
   at Intelogy___Business_Manager.v8_Tools_PDfExtractor.SimpleButton3_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by samuelGrahame** [comment]
PDF Input Management - needs to be change. only for in house use atm. as we actually put the json files inside the software now. so that all business manager user's can take advantage of them. ( i was going to keep the json files in the db but change my mind.) i will be removing publish from this screen. unless you were using it differently then i expect

**Comment by AnthonyLorraine** [comment]
No, was just seeing if functionality was working yet.
